<RidersListScreen@MDScreen>:
    size_hint: 1, .5
    pos_hint: {"top": .745}
    MDBoxLayout:
        orientation: "vertical"
        line_color: "green"
        line_width: 6
        pos_hint: {"y": .5}

        MDLabel:
            text: "Prince"
            font_size: 30

        MDLabel:
            text: "Karikari"
            font_size: 30

        MDLabel:
            text: "Awuah"
            font_size: 30
